---
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t oschku/mvp-backend ."
      - "docker tag oschku/mvp-backend 740126133497.dkr.ecr.eu-north-1.amazonaws.com/valuation-backend"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push 740126133497.dkr.ecr.eu-north-1.amazonaws.com/valuation-backend"
  pre_build: 
    commands: 
      - "echo Logging in to AWS...."
      - "docker login -u AWS -p eyJwYXlsb2FkIjoibGlhYXYyT3BGV29tNTMxLzFTZGM4bkpZQytNWUw0UmRFSVZnQWE1Rk1CWVc1YUEzMXYwMFJBZUdPYnhEanJRV3Jva29ZZ3RFS1JJT3ZpNFgxOWp1S1ZFR0lqYTR5czNsYVc1Vm5qMHNaQmR4YjdCT1Q1TWh6dzRjWUlnN2VsejRyUEIxY25CcXI0aDY0Q09ab0QwVVNrRWFuOEM3QTVvV2tKZWorVWZEY3FTaFpnWFdGbThjN0p5VWdhT1FUeUdpdHhGUWhIcnlJYnlmWnA3NzhnYW1LTGFkWXQ4cHZoY2kzbWdaY3c0eTMvNjQ3UEd0MjFlc3N0bVhXU29VU25CbXpnM1FyL2hxc2lZbXlBM2NObFVKZ0NzaGt0Z2Q5dTJ1RVl1WVBDbmFjNCtPUmFadG01T2RMODB0RFNCNnNsZGZjT0tCbFBuK0xIMmtRN2dXb2lGK3ZEdXhhVVVQWmhLZHNvYzNrWmtWWFBPQ0J5L3c0ekE2K2Jra1kvWWVnSStuVGx6d3RnLzA5Znl0SFlINEFiZmdVTVVseGRudUNUV2tGRFRCVkRwWG1MaU05eGMwTkNkV1BqR3lJcU9XOXhwRnd1RlFCL1gvYUZjWXhGT0w3b2xURWpDQk1oNXpjTjFGT2Q2WnNqR0lMbVpSaCtjR2t0VkRoMWttQWpkYW9qZC9sZ1R2dlg5SitsbWttZHhLWG9hVTd0WkIrUFZvMEVJSlErc20wNXBpSkZkK3ZiZ25Qb1dOSmdMUTB6RU83NnZvd0JHL3VOWU03WGNRYi9lVFVCa2QxeUxGejlMWDhJeHIrYVd5QVY1TDhhbzlMYlZzZ09MU2QzWEUvbEVvSGUvUFlnRUQ5akhNRVl3ZkZFMnZzeGMraFFDUnpuMWhIVmZTczExQjFpdzJCWW1pYURvc2J5NGdSbzF5R3JPZ3gyZ3U2cXd1c0dMOWRxaWF2RS9kRitVS1g4ODdZZ2FoZ0lwWFY1MGhNdWRHSzlUaHZtOGlubHNkMSt4TkNkbXMvVE5qM2pKUXhtMC94dlk5MkNzSjk1a1EyRUU2dTBmS3UvMFBibnhQeS9ZczM3akNGaWlvMTVQMU9zTUVxQU9oY0czLzlvdDFkeHY0RE96bFpIVmtLZlV3TnRNbndqcGhvYUFBbU5KcVpBYW9rWXhpUkdNRi9uN0lTNTk2NGNWWm1KOWR4OUtGRmo4K3BVdUI0ZlpaSXJtOUZUMFI5QW5meHFsdHVacHl0OTc1ZVRHTlpJUzNiVlpDUmRXWU9TUDRkcHpiS0psTGozMVIzOGN4aC9vUHdNR1JHVEhVNzJYM29WVHpuQk9jNWlOeEZjTEgyRVBnMitFYnlRd1hWT0N3eDUxVm00cEYzcHF3akFheHNja3FqSkxHNTZtMEhqWmZlV29MeC84MHhxbjBMa2VJRm9WcUQzL2F3Snp3aXlJaGdiNWZiSWRxQ3pnTERKSnpoV1dYbmEwL3VHZ1lIZEdCR2FBQjZBPT0iLCJkYXRha2V5IjoiQVFJQkFIaGZyRlEyYUlJd0Y1VmM3OVJIRVBHbmNVV3VyMi9Kek04dC9aem9FdFJyQWdIK3JRZU42RC9NaGpEU2JVeHlsNjd6QUFBQWZqQjhCZ2txaGtpRzl3MEJCd2FnYnpCdEFnRUFNR2dHQ1NxR1NJYjNEUUVIQVRBZUJnbGdoa2dCWlFNRUFTNHdFUVFNSnlSRzMwMHRLR1c2bC9Nc0FnRVFnRHZwT2ltd25ubU04SnZJVU1NNSttbU9tZEI2RXJIaVloY3ZoQWEyWTlpT0JHb0lwbURVcTBGSXBtWEpyOEVZSWJrdTFEK1RDWkpQMkw1dm13PT0iLCJ2ZXJzaW9uIjoiMiIsInR5cGUiOiJEQVRBX0tFWSIsImV4cGlyYXRpb24iOjE2MTQxMTEzMjZ9 740126133497.dkr.ecr.eu-north-1.amazonaws.com"
artifacts:
  files: 
    - "**/*"
  name: "s3-to-s3-latest-build.zip" 
version: 0.1

