---
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t oschku/mvp-build ."
      - "docker tag oschku/mvp-build 740126133497.dkr.ecr.eu-north-1.amazonaws.com/valuation-backend"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push 740126133497.dkr.ecr.eu-north-1.amazonaws.com/valuation-backend"
  pre_build: 
    commands: 
      - "echo Logging in to AWS..."
      - "docker login -u AWS -p eyJwYXlsb2FkIjoiT3VpOTdnTWpCNVdERk9hNHFMeUt2VUFhckFPS3VkZXhYZVdOOG0rTHR4dGJYWlJ1QVF5c2RnQXh0dDRTRmNvUlJzQ3UzS1h0TGI1ZHJJMGxGblF2bUwvaHdjb0YyUVlZVVppY1E4MG9qMnRqS0w3dHFjRUxndmtJb1J4M1RzMG9nc3V2Q2lSVHIvblJJbmtxTTBqb0wwQlBXMVY0UllJR0pQRjdPbjRZeUhNcGtVZDk1OFNrRk5iZENINzRtUUc4ZytlT1N6bHpVcXFVV0J2WDhoc2pUZ2IrbmVXUUJtSGxrbzFGK3ZXK0VjVnhnN3U2eG1yY3JlVUNYQWE2aklYQzQ4K3o4V3BGUHNzWDhjUmVJVDlqZnR1R0w3cmh3T09uaFIwQkU1bWptdG9sbUhyYWRaN0tUVVZldlN4ZFdmVnhSeU9CY25IYUZNaW40OXFMMmJ5RXVOd3Y4dmJSenEwNzd0Sy8wcU9qVHhCRVA3ajkvZS9NdjdwRDl1aFlyenVzcjhORVpTbkVnVHpCaXJBMElkTTRNZXZoL3hDV1Q2a1JYU2VPT2hHN3N3cUFYeFpvRUpFUEgvdU9DcU9Oa1VWMkprSTVSN1BaWW9vaUJTMm03Zjg2QkJJWm9Vb1FPSis2L1pLWkp4dWxzOVZXbjBRWDVGbGRGdG9ZL3NCWXVOS1VReUZXK3VzdTRmdkJCOFlnVC8zaHZnbkp5Ylc5OG9RNDhNbklWNUhRcUIrR3hmWHVuRXdKR1ZGZ09hcVpBcnc2UzdwUzZkZ3NheEtGRmtZWnB2YUM0QkVmR2lXRmhWekppYTNWTEZnZ2FmajFaRWtLeUZVR0J6S0JZN1BpbEhWOXg5S1hqSVVJU096Z2U4dDlaUkJhSXhlTUVxQWtuU00rM09LSUhTVHRDcWpkUW9uRTZyeTgxeC8vMXVSb0NvQmV6YU1kbmFvM2drNlNjZU1lbEVKdEYxRjhVOEwyV1I2Y2JvNFpBZjdtUDRQeForWTRpb2hkeU16L3hmRkRock5EUytFenhJUW9GeW4xOVl4V3pxM1BKUzhrMnJlbnExemZtRW5QVlJIeFVBdlp1NjFkWTdvS2Vxek9Xd1BMYlVBenRORDNYWjhHcDVPSUhVSVk0SWxvL0t2U1F3VjcyeE5aWW1TbW81WEkxeDJSTXZHS2tyL2Q0VjJSZXF5ejFmTi8xeUxHaFdYTU1ERTgvWStVK2Fzdjgxc050QXdTSi9mS2xpSGl4Zi95TDhHRG5lczI1a01hallzSXRiTWxydkxMUDV1cnk3cEtyVmNXNUxHZUlpaUtzNFM3eTJXNVliVDY3UjBzUk43Mm1KRzRtTXFXVW83OVd1UjhpZ0ZaTmVlZTRaRkd1aXE0cEhXNEJUQThMUUdIemZiMndMMkd4aG1NSkxuUGJHVzBHRmNKV0gvdUJqZk9LT2I4WFM2eDRYKzNkSHE2anNkd08zVUlUVzYyV3c9PSIsImRhdGFrZXkiOiJBUUlCQUhoZnJGUTJhSUl3RjVWYzc5UkhFUEduY1VXdXIyL0p6TTh0L1p6b0V0UnJBZ0ZlL3lKVlU3MG0zWDdPRmg0Ly9RbWRBQUFBZmpCOEJna3Foa2lHOXcwQkJ3YWdiekJ0QWdFQU1HZ0dDU3FHU0liM0RRRUhBVEFlQmdsZ2hrZ0JaUU1FQVM0d0VRUU1CbWJyd1pFdmhITzkySzN5QWdFUWdEc1RJM0UyV29mdDlma043T2hVeGwvMzNYQ2FuQytOMGxDMWExeTh3OG1IZFlzSmh0YjN2SnJ2RmRIVXZNQ0tHeFg3SjROR2JLcE1yNEp6Q0E9PSIsInZlcnNpb24iOiIyIiwidHlwZSI6IkRBVEFfS0VZIiwiZXhwaXJhdGlvbiI6MTYxMzUxODI0Nn0= 740126133497.dkr.ecr.eu-north-1.amazonaws.com"
artifacts:
  files: 
    - "**/*"
  name: "s3-to-s3-latest-build.zip" 
version: 0.1

