---
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t oschku/mvp-backend ."
      - "docker tag oschku/mvp-backend 740126133497.dkr.ecr.eu-north-1.amazonaws.com/valuation-backend"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push 740126133497.dkr.ecr.eu-north-1.amazonaws.com/valuation-backend"
  pre_build: 
    commands: 
      - "echo Logging in to AWS...."
      - "docker login -u AWS -p eyJwYXlsb2FkIjoiK05mYlBLa3BrTnJXQjE2MTVXdHYwTFY4VkJLRXREV3QvWTRBbHMyZFlUcTZKdEx2d1gzcU5zNmVtcVN3dGRXZDdJM3pMWHJybmFlU0lVaWhHQ2t4dzRSY3lwMmZxRUJZemprbVdvdjJ0Rll5NHZoUDhONzVRQzJoaEd0emJJT3RCOGxBWTRBQ0h5NGtDS3BIeDV5dHNIaThiTUt3TWRtWnFxQ3o4MUZLZXFhSGVWVFNvMzZGSlA1TWlZV1NVSWpsZDg4dEx4YlVJWUdzL3pkclk2RG5SYjFydGpkYVRXbTJkajVYTzRPb1IzUEdaeUJMOGxScVJPWkVzVFpMSG8rVE9MZHZwMTNscjF6Rktna1FodTdnT2N4N016dFc2QTdTVVhENWNMKzFNbm5zOG5JV3A1T3dkeXJVRENGVmIvY3RQSENlQ1dWa1h2THlHMTZzYktKVElBUVN6Yk9adllQSkVzRkRyYzNHMXM5OGVpQUxvemRET1F5UXpUeUtVY3NIdU1ZY0YxbGtKV3ZHR2k5VjZKWWdtQ1hSM0tlZ3RhaVBZS3ZobkNSMGxkTkNWb2VEUlZ5dkM2Wm1RRy9CN1dlSVRQSGtUM3VFWE9nN2JLSVV3YkJQalFJanJTMG13TmpJSjJhR1FUcGhOMU1naDlTVzVLOStQSXlYQ1Qray9DOUlPRit3OU1TcEc0ME12MmJPSjlGNU9vd0ZBaWk1cEwwblJxbWkwS1hOODNHWFZ1SkhRU0w3VXAwQVh1WWVTa2kyZW1WbTB6M29haVhwNitIWk82em0wbHBzRTJVbEFoT1RpWGNGSGxQUFJOdnBxNG9FelBDVWM0Y2VRN1kxNXM5MGR1NUxEQzdqQURYc1ViNjRrc0d1cEdZNHBRVWFPRE5Xend6dkhrOGdUYjc2dFY2UGd6NVVROXJQaEhDbVcya0FOb0thZm9UdzZRL0lrSUpGci9hbm5ReWk3TGVXN0RYZ3RHNjRoNVhDN2FvcCtUTUpzVVJsTHBpNmQrVzhNR1lKeHA5YmVpYUxiazVkOFZTZmFkc0FqTkI1V1RnSi9pQTBsWUV3eHJyQ3NsOFBYSFAvWXl4Y3ZhWGlIYW1rNUxuRC9tUmRFRzBKVkY3QVVqZ2d2alZuMzJMMzl5NWQ4cWVkT2c2ZEJXc2pFR3VwdU43WmhrcmFBeE5EcVR4S0duNkMrcXVERS9qZ3A2WmFDeHBGNEh4bTE5OTZsejZDYUROVzdsMkNodzZXMS9jbUdTcW92UldES2FmdnJGbHVqK25UQStvQ1ArbThaWHlkOFNERk1veU5BVExSRzdqeExucjFralA2NHlHWkR6cnRqdlBKQnU4dCtyT3d0UTJzbStSUkpYSEd1VEtHa2pPbUhST2lua2FPN3A0RGVLV1h2QzExdXQyVWRkSms1T0RmWmIySllZSkljTTd4aHNIc0xnOGt1Q2hidVp4SGdCS05ITzRWcTd0SGgxcjFzeWhTNFRsaVJ3PT0iLCJkYXRha2V5IjoiQVFJQkFIaGZyRlEyYUlJd0Y1VmM3OVJIRVBHbmNVV3VyMi9Kek04dC9aem9FdFJyQWdIRnhPYms4RXo4QXhwaU9aNFA2dW4rQUFBQWZqQjhCZ2txaGtpRzl3MEJCd2FnYnpCdEFnRUFNR2dHQ1NxR1NJYjNEUUVIQVRBZUJnbGdoa2dCWlFNRUFTNHdFUVFNNjJFR0FMQWFWR2VIOWVxUUFnRVFnRHVveFY0b01qTGdrSm9RWEJmalVXZ1p0WDJoamVUNGpHajJZc2NpY0VhanFKOFhURFUrNGtQRlQwNmdycFNvRmtXNnluZUo3ZnZVRk5hRWVRPT0iLCJ2ZXJzaW9uIjoiMiIsInR5cGUiOiJEQVRBX0tFWSIsImV4cGlyYXRpb24iOjE2MTM3MDYyNDR9 740126133497.dkr.ecr.eu-north-1.amazonaws.com"
artifacts:
  files: 
    - "**/*"
  name: "s3-to-s3-latest-build.zip" 
version: 0.1

